spring:
  datasource:
    # Docker Compose에서 5432 포트를 열어두었으므로 localhost로 접속 가능
    url: jdbc:postgresql://localhost:5432/chatdb
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # 개발용 설정 (운영 시에는 validate 또는 none 권장)
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
